Update cortexcli.yml

diff --git a/.github/workflows/cortexcli.yml b/.github/workflows/cortexcli.yml
--- a/.github/workflows/cortexcli.yml
+++ b/.github/workflows/cortexcli.yml
@@ -42,13 +42,14 @@ jobs:
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5
 
-    - name: Build Image and export image ID
+    - name: Build Image
       run: |
         docker build -t $IMAGE_NAME .
 
     - name: Cortex CLI Image Scan
       run: |
         results=$(./cortexcli \
+          --soft-fail \
           image scan \
           --timeout 600 \
           --name $IMAGE_NAME \
@@ -56,7 +57,9 @@ jobs:
           --pipeline-id ${{ github.repository_id }} \
           --output-format json \
           $IMAGE_NAME)
-
+        echo "Ouput error if any"
+        cat $HOME/.cortexcli/logs/cortexcli-*.log | grep "ERROR" || echo "No error found"
+        
         echo "Storing results"
         mkdir results
         echo "$results" | sed -n 's/.*<SCAN_INTRO_START>\(.*\)<SCAN_INTRO_END>.*/\1/p' | jq . > results/scanIntro.json
@@ -64,7 +67,6 @@ jobs:
 
     - name: Uploade results
       uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
-      if: success() || failure()
       with:
         name: cwp-results
         path: ./results
