fixed test CWP only

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -58,4 +58,4 @@ jobs:
 
     # Output any error found
     - name: Check CortexCLI Error logs
-      run: cat $HOME/.cortexcli/logs/cortexcli-*.log | grep "ERROR"
+      run: cat $HOME/.cortexcli/logs/cortexcli-*.log | grep "ERROR" || echo "No error found"
