feat: Included output report for vulnerabilities detected (CWP Only)

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,4 +1,4 @@
-name: Docker Image CI
+name: Image Scan CortexCLI
 
 permissions: {}
 
@@ -7,22 +7,21 @@ on:
     branches:
       - cortex-cli
   workflow_dispatch:
-  
     
 jobs:
   docker:
     runs-on: ubuntu-latest
-    environment: Cortex
     env:
-        CORTEX_API_KEY: ${{secrets.CORTEX_API_KEY}}
-        CORTEX_API_KEY_ID: ${{secrets.CORTEX_API_KEY_ID}}
-        CORTEX_API_URL: ${{secrets.CORTEX_API_URL}}
+      CORTEX_API_KEY: ${{ secrets.CORTEX_API_KEY }}
+      CORTEX_API_KEY_ID: ${{ secrets.CORTEX_API_KEY_ID }}
+      CORTEX_API_URL: ${{ secrets.CORTEX_API_URL }}
+      WAIT: ${{ vars.WAIT || 600 }}
+      IMAGE_NAME: "${{ vars.IMAGE_NAME }}:latest"
 
     steps:
     # Initial Setup
     - name: Checkout
       uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5
-
 
     - name: Download cortexcli
       run: |
@@ -33,31 +32,9 @@ jobs:
         chmod +x cortexcli
         ./cortexcli --version
 
-    # Do AppSec Code Scanning
-    - name: Set up Node.js
-      uses: actions/setup-node@d7a11313b581b306c961b506cfc8971208bb03f6
-      with:
-        node-version: 22
-
-    - name: Verify Node.js Version
-      run: node -v
-      
-    - name: Run Cortex CLI Code Scan
-      run: |
-        ./cortexcli \
-          --api-base-url "${CORTEX_API_URL}" \
-          --api-key "${CORTEX_API_KEY}" \
-          --api-key-id "${CORTEX_API_KEY_ID}" \
-          code scan \
-          --directory "${{github.workspace}}" \
-          --repo-id "${{github.repository}}" \
-          --branch "${{github.ref_name}}" \
-          --source "GITHUB_ACTIONS" \
-          --create-repo-if-missing
-
     # Do CWP image scanning
     - name: CWP Image Scan Dependency
-      run: sudo apt install libhyperscan5 -y
+      run: sudo apt install libhyperscan5 jq -y
       
     - name: Set up QEMU
       uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf
@@ -65,19 +42,104 @@ jobs:
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5
 
-    - name: Build and Run Cortex CLI Image Scan
+    - name: Build Docker image
+      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
+      with:
+        push: false
+        tags: ${{ env.IMAGE_NAME }}
+
+    - name: Check Image in Cortex Cloud
+      id: check_image
       run: |
-        docker build -t ${{vars.IMAGE_NAME}}:latest .
-        sudo ./cortexcli \
+        image_id=$(docker inspect $IMAGE_NAME --format='{{.Id}}')
+        echo "Searching if the image $IMAGE_NAME exists in Cortex Cloud. Digest: $image_id..."
+        asset_info=$(curl -s -X POST -H "Content-Type: application/json" -H "Authorization: ${CORTEX_API_KEY}" -H "x-xdr-auth-id: ${CORTEX_API_KEY_ID}" "${CORTEX_API_URL}/public_api/v1/assets" -d '
+          {
+              "request_data": {
+                  "filters": {
+                      "AND": [
+                          {
+                              "SEARCH_FIELD": "xdm.asset.name",
+                              "SEARCH_TYPE": "EQ",
+                              "SEARCH_VALUE": "'$image_id'"
+                          }  
+                      ]
+                  },
+                  "search_from": 0,
+                  "search_to": 0
+              
+              }
+          }' | jq -r '.reply.data[]')
+        [[ -z "$asset_info" ]] && image_found="false" || image_found="true"
+
+        echo "IMAGE_ID=$image_id" >> $GITHUB_ENV
+        echo "image_found=$image_found" >> $GITHUB_OUTPUT
+
+
+    - name: Cortex CLI Image Scan
+      if: ${{ steps.check_image.outputs.image_found == 'false' }}
+      run: |
+        image_id=$(sudo ./cortexcli \
           --api-base-url "${CORTEX_API_URL}" \
           --api-key "${CORTEX_API_KEY}" \
           --api-key-id "${CORTEX_API_KEY_ID}" \
           --soft-fail \
           image scan \
           --timeout 600 \
-          --name ${{vars.IMAGE_NAME}}:latest \
-          ${{vars.IMAGE_NAME}}:latest
+          --output-format json \
+          --name $IMAGE_NAME \
+          $IMAGE_NAME | grep -oP '(?<="image_id":")[^"]*')
+        echo "IMAGE_ID=$image_id" >> $GITHUB_ENV
 
     # Output any error found
-    - name: Check CortexCLI Error logs
-      run: cat $HOME/.cortexcli/logs/cortexcli-*.log | grep "ERROR" || echo "No error found"
+    - name: Check CortexCLI Error and Wait for results
+      if: ${{ steps.check_image.outputs.image_found == 'false' }}
+      run: | 
+        echo "Errors:"
+        cat $HOME/.cortexcli/logs/cortexcli-*.log | grep "ERROR" || echo "No error found"
+        echo "Waiting for Cortex to process image $IMAGE_NAME. Image Id: ${IMAGE_ID}"
+        sleep ${WAIT}
+
+
+    - name: Get Results
+      run : |
+        echo "Obtaining findings of image: $IMAGE_NAME. Image Id: $IMAGE_ID"
+        start_response=$(curl -s -X POST -H "Content-Type: application/json" -H "Authorization: ${CORTEX_API_KEY}" -H "x-xdr-auth-id: ${CORTEX_API_KEY_ID}" "${CORTEX_API_URL}/public_api/v1/xql/start_xql_query" -d '
+            {
+                "request_data": {
+                    "query": "dataset = uvm_findings | filter asset_name = \"'$IMAGE_ID'\" | dedup vulnerability_id, package_purl"
+                }
+            }')
+        query_id=$(echo "$start_response" | jq -r '.reply')
+
+        if [[ "$query_id" == "null" || -z "$query_id" ]]; then
+            echo "❌ Failed to start XQL query. Response details:"
+            echo "$start_response"
+            exit 1
+        fi
+
+        echo "XQL Query started successfully. Query ID: ${query_id}"
+
+
+        # Define initial status
+        echo "Retrieving results for Query ID: ${query_id}. Waiting for completion (pending_flag=true)..."
+        status="PENDING"
+
+        while [[ "$status" == "PENDING" ]]; do
+            # Execute API call to get results
+            results_response=$(curl -s -X POST -H "Content-Type: application/json" -H "Authorization: ${CORTEX_API_KEY}" -H "x-xdr-auth-id: ${CORTEX_API_KEY_ID}" "${CORTEX_API_URL}/public_api/v1/xql/get_query_results" -d '
+                {
+                    "request_data": {
+                        "query_id": "'$query_id'", 
+                        "pending_flag": true, 
+                        "limit": 100, 
+                        "format": "json"
+                    }
+                }')
+            status=$(echo "$results_response" | jq -r '.reply.status')
+            sleep 10
+        done
+
+        echo "Status: $status"
+        # Print the full response for troubleshooting
+        echo "$results_response" | jq .
